#include <boost/python.hpp>
using boost::python::class_;
using boost::python::enum_;
using boost::python::scope;

extern "C"
{
    #include "orpginfo.h"
}

#include "wrap_orpg_info.h"

namespace rpg
{
    void export_orpginfo()
    {
        scope in_orpginfo = class_<orpginfo_ns>("orpginfo");
        enum_<Orpginfo_statefl_rpgalrm_t>("orpgalarms")
            .value("ORPGINFO_STATEFL_RPGALRM_NONE", ORPGINFO_STATEFL_RPGALRM_NONE)
            .value("ORPGINFO_STATEFL_RPGALRM_NODE_CON", ORPGINFO_STATEFL_RPGALRM_NODE_CON)
            .value("ORPGINFO_STATEFL_RPGALRM_WBFAILRE", ORPGINFO_STATEFL_RPGALRM_WBFAILRE)
            .value("ORPGINFO_STATEFL_RPGALRM_RPGCTLFL", ORPGINFO_STATEFL_RPGALRM_RPGCTLFL)
            .value("ORPGINFO_STATEFL_RPGALRM_DBFL", ORPGINFO_STATEFL_RPGALRM_DBFL)
            .value("ORPGINFO_STATEFL_RPGALRM_WBDLS", ORPGINFO_STATEFL_RPGALRM_WBDLS)
            .value("ORPGINFO_STATEFL_RPGALRM_PRDSTGLS", ORPGINFO_STATEFL_RPGALRM_PRDSTGLS)
            .value("ORPGINFO_STATEFL_RPGALRM_RDAWB", ORPGINFO_STATEFL_RPGALRM_RDAWB)
            .value("ORPGINFO_STATEFL_RPGALRM_RPGRPGFL", ORPGINFO_STATEFL_RPGALRM_RPGRPGFL)
            .value("ORPGINFO_STATEFL_RPGALRM_REDCHNER", ORPGINFO_STATEFL_RPGALRM_REDCHNER)
            .value("ORPGINFO_STATEFL_RPGALRM_RPGTSKFL", ORPGINFO_STATEFL_RPGALRM_RPGTSKFL)
            .value("ORPGINFO_STATEFL_RPGALRM_MEDIAFL", ORPGINFO_STATEFL_RPGALRM_MEDIAFL)
            .value("ORPGINFO_STATEFL_RPGALRM_RDAINLS", ORPGINFO_STATEFL_RPGALRM_RDAINLS)
            .value("ORPGINFO_STATEFL_RPGALRM_RPGINLS", ORPGINFO_STATEFL_RPGALRM_RPGINLS)
            .value("ORPGINFO_STATEFL_RPGALRM_FLACCFL", ORPGINFO_STATEFL_RPGALRM_FLACCFL)
            .value("ORPGINFO_STATEFL_RPGALRM_DISTRI", ORPGINFO_STATEFL_RPGALRM_DISTRI)
    ;

        enum_<Orpginfo_statefl_rpgopst_t>("opstatus")
            .value("ORPGINFO_STATEFL_RPGOPST_LOADSHED", ORPGINFO_STATEFL_RPGOPST_LOADSHED)
            .value("ORPGINFO_STATEFL_RPGOPST_ONLINE", ORPGINFO_STATEFL_RPGOPST_ONLINE)
            .value("ORPGINFO_STATEFL_RPGOPST_MAR", ORPGINFO_STATEFL_RPGOPST_MAR)
            .value("ORPGINFO_STATEFL_RPGOPST_MAM", ORPGINFO_STATEFL_RPGOPST_MAM)
            .value("ORPGINFO_STATEFL_RPGOPST_CMDSHDN", ORPGINFO_STATEFL_RPGOPST_CMDSHDN)
    ;
    }
}

